Traceback (most recent call last):
  File "/home/bzhao/Deep-Learning/Assignment2/src/train.py", line 273, in <module>
    main()
  File "/home/bzhao/Deep-Learning/Assignment2/src/train.py", line 268, in main
    best_ckpt = train(args)
                ^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/src/train.py", line 93, in train
    trainer.fit(model, dm)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 560, in fit
    call._call_and_handle_interrupt(
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 49, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 598, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 108, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 199, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/src/datamodule_oxpet.py", line 164, in setup
    train_transform = get_heavy_augmentation(self.img_size)
                      ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_heavy_augmentation' is not defined
